### ISSUE TITLE
unable to resolve dependency tree

### ISSUE THREAD

**Issue by 0x11c11e** [mantinedev/next-pages-template#13]
user@user:~/Code/main-website$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: mantine-next-template@1.0.0
npm ERR! Found: react@18.1.0
npm ERR! node_modules/react
npm ERR!   react@"18.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.x || ^17.x" from @modulz/radix-icons@4.0.0
npm ERR! node_modules/@modulz/radix-icons
npm ERR!   @modulz/radix-icons@"^4.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/user/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2022-05-19T20_58_13_094Z-debug-0.log

os: debian
ide: vscode

**Comment by rtivital** [comment]
Use yarn with this template and it will work fine

**Comment by Maetes** [comment]
If you want to use, you can also do a `npm install --legacy-peer-deps`
