### ISSUE TITLE
How to setup system color mode?

### ISSUE THREAD

**Issue by siamahnaf** [mantinedev/next-pages-template#23]
This template not working with system color mood. If browser theme is dark theme, then it should automatically load with dark mode and vice versa.

Please give an example.

**Comment by rtivital** [comment]
https://mantine.dev/guides/dark-theme/#detect-user-preferred-color-scheme

**Comment by siamahnaf198** [comment]
Okay, thanks. Please help me one more things.

**Comment by siamahnaf198** [comment]
When I use this in `_app.tsx`

```
import { ColorScheme, ColorSchemeProvider, Global, MantineProvider } from '@mantine/core'
import { getCookie, setCookie } from 'cookies-next'
import { GetServerSidePropsContext } from 'next'
import { ThemeProvider } from 'next-themes'
import { AppProps } from 'next/app'
import { useState } from 'react'

type Props = AppProps & { colorScheme: ColorScheme }

export default function App({ Component, pageProps, colorScheme: _colorScheme }: Props) {
  const [colorScheme, setColorScheme] = useState<ColorScheme>(_colorScheme)

  const toggleColorScheme = (value?: ColorScheme) => {
    const nextColorScheme = value || (colorScheme === 'dark' ? 'light' : 'dark')
    setColorScheme(nextColorScheme)
    setCookie('mantine-ui-colorScheme', nextColorScheme, { maxAge: 60 * 60 * 24 * 30 })
  }

  return (
    <>
      {/* need add next-themes failback */}
      <Global styles={() => ({
        ':root': { background: '#fff', color: '#000' },
        '[data-theme="dark"]': { background: '#1A1B1E', color: '#C1C2C5' }
      })} />
      {/* next-themes theme provider */}
      <ThemeProvider enableSystem={false}>
        {/* mantine color scheme provider */}
        <ColorSchemeProvider colorScheme={colorScheme} toggleColorScheme={toggleColorScheme}>
          <MantineProvider theme={{ colorScheme }} withGlobalStyles withNormalizeCSS>
            <Component {...pageProps} />
          </MantineProvider>
        </ColorSchemeProvider>
      </ThemeProvider>
    </>
  )
}
App.getInitialProps = ({ ctx }: { ctx: GetServerSidePropsContext }) => ({
  colorScheme: getCookie('mantine-ui-colorScheme', ctx) || 'light',
})
```

I am getting one next js warning.

`Warning: You have opted-out of Automatic Static Optimization due to `getInitialProps` in `pages/_app`. This does not opt-out pages with `getStaticProps``

Can we get rid of this warning.

**Note: This warning appears when I build the next js app

**Comment by rtivital** [comment]
No, next-themes is not supported

**Comment by siamahnaf198** [comment]
https://mantine.dev/guides/dark-theme/#detect-user-preferred-color-scheme this is not support with SSR!

**Comment by rtivital** [comment]
Yes, it is correct, to support ssr use color scheme with cookie, there is no way of knowing user preferred color scheme on the server.

**Comment by siamahnaf198** [comment]
Okay. Then How can I remove get rid of warning when I try to use with cookies.

**Comment by rtivital** [comment]
You do not, ssr is required for cookie to work

**Comment by siamahnaf198** [comment]
Ohh, Okay. Thanks. I am facing difficulties to use mantine with next js.

https://next-themes-example.vercel.app/
They know browser theme even they are on the server. I think you guys should give this feature with mantine. Then mantine can be more usefull.

**Comment by rtivital** [comment]
From the https://www.npmjs.com/package/next-themes

<img width="733" alt="image" src="https://user-images.githubusercontent.com/10353856/196697377-8304483e-0c78-43e7-8fed-455226dcdbf5.png">

**Comment by siamahnaf198** [comment]
But they give not flashing dark mode with system theme. I just want to get no flashing dark mode experience with mantine (also with system theme)
